/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConsortiumRouteImport } from './routes/consortium'
import { Route as IndexRouteImport } from './routes/index'

const ConsortiumRoute = ConsortiumRouteImport.update({
  id: '/consortium',
  path: '/consortium',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consortium': typeof ConsortiumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consortium': typeof ConsortiumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consortium': typeof ConsortiumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/consortium'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/consortium'
  id: '__root__' | '/' | '/consortium'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsortiumRoute: typeof ConsortiumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/consortium': {
      id: '/consortium'
      path: '/consortium'
      fullPath: '/consortium'
      preLoaderRoute: typeof ConsortiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsortiumRoute: ConsortiumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
